### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [Luccifer/SonogramView#1]
Hey @SonogramView, your lib is awesome but your README lacks an installation section
I created this [iOS README template](https://github.com/awesome-labs/iOS-readme-template) to help you out 😉 

Please fix this issue before we can approve [the AwesomeiOS PR](https://github.com/vsouza/awesome-ios/pull/1941)

**Comment by Luccifer** [comment]
Done! Ty for mentoring!
