### ISSUE TITLE
Documentation missing on how to animate

### ISSUE THREAD

**Issue by ekscrypto** [Luccifer/SonogramView#7]
Hello, looking at the code there seems to be a shapeLayer added to the view which would allow for some kind of animation.  I'm guessing the intent was to allow changing the color of the sonogram view while playing the audio clip.  Do you have any sample code on how to achieve this effect?

**Comment by Luccifer** [comment]
Hi there! Actually I was planned to add animation to this lib, cause in real-battleprooved project we have such functional like animation and color changing. 
In short: You can add layer behind the audiogram with the color u want and animate it left-right, just check that ur "pathS" of audiogram are clearColor + their frame is any other color from animatable and static one

**Comment by Luccifer** [comment]
closed, feel free to open new one if you still need it!
